# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := gtkglext
### Rules for final target.
$(obj).target/gtkglext.stamp: TOOLSET := $(TOOLSET)
$(obj).target/gtkglext.stamp:  FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/gtkglext.stamp
# Add target alias
.PHONY: gtkglext
gtkglext: $(obj).target/gtkglext.stamp

# Add target alias to "all" target.
.PHONY: all
all: gtkglext

